/data/ohsung/repos/llm
/data/ohsung/anaconda3/envs/llm/bin/python
augi1
Traceback (most recent call last):
  File "/data/ohsung/repos/llm/original.py", line 2, in <module>
    forum_messages_df = pd.read_csv('/local_datsets/llm/ForumMessages.csv')
  File "/data/ohsung/anaconda3/envs/llm/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/data/ohsung/anaconda3/envs/llm/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/data/ohsung/anaconda3/envs/llm/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/data/ohsung/anaconda3/envs/llm/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/data/ohsung/anaconda3/envs/llm/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/local_datsets/llm/ForumMessages.csv'
